[package]
name = "anchor-chain"
version = "0.2.0"
edition = "2021"
description = "A statically typed async framework for building LLM-based applications."
license = "MIT"
repository = "https://github.com/emersonmde/anchor-chain"
documentation = "https://errorsignal.dev/anchor-chain/anchor_chain/"
readme = "README.md"
keywords = ["llm", "langchain", "rag", "openai", "claude"]
categories = ["development-tools", "api-bindings", "asynchronous", "concurrency"]
authors = ["Matthew Emerson <emersonmde@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.81"
async-openai = "0.19.1"
async-trait = "0.1.79"
aws-config = { version = "1.1.9", features = ["behavior-version-latest"] }
aws-sdk-bedrockruntime = "1.19.0"
futures = "0.3.30"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tera = "1.19.1"
tokio = { version = "1.36.0", features = ["full"] }
