[package]
name = "anchor-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "anchor_chain"
path = "src/lib.rs"


[[bin]]
name = "anchor-chain"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.81"
async-openai = "0.19.1"
async-trait = "0.1.79"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
