[package]
name = "anchor-chain-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.66", features = ["full"] }
quote = "1.0"
serde_json = "1.0"
proc-macro2 = "1.0.85"
proc-macro-crate = "3.1.0"